import { defineStore } from "pinia";

export const useProductsStore = defineStore("products", {
  state: () => ({
    products: [
      {
        id: 1,
        name: "Silk Evening Gown",
        category: "Dresses",
        price: 1299.99,
        originalPrice: 1899.99,
        image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600",
        description: "Elegant floor-length silk gown with delicate hand-stitched details.",
        rating: 4.8,
        reviews: 124,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["Black", "Ivory"],
        featured: true,
      },
      {
        id: 2,
        name: "Cashmere Wool Coat",
        category: "Outerwear",
        price: 1899.99,
        originalPrice: 2499.99,
        image: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600",
        description: "Luxurious double-breasted coat in pure cashmere wool.",
        rating: 4.9,
        reviews: 89,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Charcoal"],
        featured: true,
      },
      {
        id: 3,
        name: "Italian Leather Jacket",
        category: "Outerwear",
        price: 2199.99,
        originalPrice: 2899.99,
        image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600",
        description: "Premium Italian leather jacket with silk lining.",
        rating: 4.7,
        reviews: 156,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["Black"],
        featured: true,
      },
      {
        id: 4,
        name: "Designer Trousers",
        category: "Pants",
        price: 699.99,
        originalPrice: 899.99,
        image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600",
        description: "Tailored high-waist trousers in premium wool blend.",
        rating: 4.5,
        reviews: 67,
        sizes: ["XS", "S", "M", "L"],
        colors: ["Black", "White", "Gray"],
        featured: false,
      },
      {
        id: 5,
        name: "Pure Linen Shirt",
        category: "Shirts",
        price: 399.99,
        originalPrice: 549.99,
        image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600",
        description: "Classic button-down shirt in premium Egyptian linen.",
        rating: 4.6,
        reviews: 93,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["White", "Black"],
        featured: false,
      },
      {
        id: 6,
        name: "Velvet Blazer",
        category: "Blazers",
        price: 1599.99,
        originalPrice: 1999.99,
        image: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600",
        description: "Luxurious velvet blazer with satin lapels.",
        rating: 4.9,
        reviews: 45,
        sizes: ["XS", "S", "M", "L"],
        colors: ["Black", "Burgundy"],
        featured: true,
      },
      {
        id: 7,
        name: "Silk Midi Skirt",
        category: "Skirts",
        price: 599.99,
        originalPrice: 799.99,
        image: "https://images.unsplash.com/photo-1583496661160-fb5886a0a1f0?w=600",
        description: "Flowing midi skirt in pure mulberry silk.",
        rating: 4.7,
        reviews: 78,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["Black", "White"],
        featured: false,
      },
      {
        id: 8,
        name: "Merino Wool Sweater",
        category: "Knitwear",
        price: 499.99,
        originalPrice: 699.99,
        image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600",
        description: "Luxuriously soft merino wool turtleneck sweater.",
        rating: 4.6,
        reviews: 112,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Gray"],
        featured: false,
      },
    ],
    categories: ["All", "Dresses", "Outerwear", "Pants", "Shirts", "Blazers", "Skirts", "Knitwear"],
  }),

  getters: {
    featuredProducts: (state) => state.products.filter((p) => p.featured),
    productsByCategory: (state) => (category) => {
      if (category === "All") return state.products;
      return state.products.filter((p) => p.category === category);
    },
  },
});
